name: Publish to Maven

on:
  release:
    types: [created]
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: maven
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Checkout Maven repository
        uses: nbcss/maven/.github/actions/setup-maven-repo@main
        with:
          token: ${{ secrets.MAVEN_REPO_GITHUB_TOKEN }}
          path: maven-repository

      - name: Publish package
        run: ./gradlew publish
        env:
          MAVEN_REPO_PATH: ${{ github.workspace }}/maven-repository

      - name: Push to Maven repository
        uses: nbcss/maven/.github/actions/push-maven-repo@main
        with:
          token: ${{ secrets.MAVEN_REPO_GITHUB_TOKEN }}
          path: maven-repository
